//
// Created by Patrick Tumulty on 5/29/22.
//

#ifndef RHC_PLACEHOLDERS_H
#define RHC_PLACEHOLDERS_H

#define PLACEHOLDER_DATA_INIT_STRING "PLACEHOLDER_DATA_INIT"
#define PLACEHOLDER_DATA_INIT ;

#define PLACEHOLDER_CONTENTS_START_STRING "PLACEHOLDER_CONTENTS_START"
#define PLACEHOLDER_CONTENTS_START ;

#define PLACEHOLDER_CONTENTS_END_STRING "PLACEHOLDER_CONTENTS_END"
#define PLACEHOLDER_CONTENTS_END ;

#endif //RHC_PLACEHOLDERS_H
